ccflags-y += -I$(srctree)/drivers/misc/mediatek/alsps/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/nubia_sensor

obj-y	:=  ams_tmd2725.o ams_tmd2725_ic.o ams_tmd2725_prox.o ams_tmd2725_als.o ams_i2c.o
